# Plain TOML config for helix
# got annoyed with nix syntax

theme = "kanagawa"

[editor]
line-number = "relative"
completion-replace = true
rulers = [80]
color-modes = true
soft-wrap.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "all"

[editor.whitespace.characters]
tab = "→"
newline = "⏎"

[editor.indent-guides]
render = true


[keys.normal]
#C-s = ":w"

# append a ';' to the end of a line and enter insert mode on the next line
";"= ["goto_line_end", ":append-output echo ';'", "open_below", "insert_mode"]
# overrides 'collapse_selection'

# version that keeps the cursor in place
#A-; = ["save_selection", "goto_line_end", ":append-output echo -n ';'", "jump_backward"]

[keys.insert]

